name: do_not_use_var
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer:
  analyzer_plugin:
  custom_lint_builder:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  path: ^1.9.0
  stack_trace: ^1.12.1
